[사칙연산] 첫번째 로직 구현
hhlyn0328/racingcar-practice pull request #1
Opened 2020-12-11 00:03 UTC by eeunheechoi

2020-12-11 01:26 UTC, hhlyn0328 requested changes
오 객체를 열심히 나눠보셨네요 👏 
고생하셨어요 
몇 가지 코멘트드렸습니다 확인 부탁드려요

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Calculate.java
> +    public static int calculate() {
내부변수 선언과 Constructor를 제공하고 Calculate.calculate(1, "+", 2) 로 사용해도 될 거 같습니다
객체명은 Calculator 와 같은 명사로 선언해주세요 

저도 똑같이 저번 강의를 기억하며 내부 변수 선언했다가 아래와 같이 코멘트를 받았습니다 ㅋㅋ

```
객체에 값을 설정한다
계산한다
이렇게 분리해서 구현하셨는데 그럴 필요는 없어보여요
calculator가 피연산자, 연산자를 인스턴스 변수로 들고 있을 필요도 없어보이네요
```

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Formula.java
> +            if(idx == 0) {
firstNo 초기값 셋팅을 while 문 밖에서 선언하고 
idx를 1부터 시작해보면 이 if-else 문이 제거 될 수 있을 거 같아요 
그럼 객체지향 생활체조 원칙 1번 한단계의 들여쓰기만 한다.  를 만족할 수 있을 것 같습니다

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Formula.java
> +            sign = getSign(++idx);
for (int i = 1; i < formula.length; i += 2)
sign = getSign(i)
lastNo = getNumber(i+1)

과 같이 하면 반복문에서만 사용되는 index 선언이 반복문 밖에서 선언되지 않아도 될 거 같아요 

위의 2 + 3 * 4 / 2 를 했을 때 
firstNo = 2 
i = 1 ) getSign (1) = + , getNumber(2) = 3, firstNum(result) = 2+3 //  i += 2 =>  3 < length(7) : true
i = 3 ) getSign (3) = * , getNumber(4) = 4, firstNum(result) = 5 * 4 // i +=2 => 5 < length(7) : true
i = 5 ) getSign (5) = / , getNumber(6) = 2, firstNum(result)  = 10 / 2 // i +=2 => 7 < length(7) : false

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Formula.java
> +            Calculate cal = new Calculate(firstNo, sign, lastNo);
parameter에 바로 getSign, getNumber를 넘기면 별도의 변수를 선언하고 
계속 덮어쓰지 않아도 될 것 같아요

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Formula.java
> +    public boolean isSign(String aa) {
calculate method만 참조하는 내부의 method들은  private으로 선언하는것은 어떨까요

2020-12-11 01:26 UTC, hhlyn0328 commented on src/test/java/ValidationUtilsTest.java
> +        Formula formula = new Formula(null);
2 % 3 과같이 사칙연산이 아닌 것과  0으로 나누는 케이스에 대한 validation과 테스트도 해보면 좋을거 같아요 
그리고 validationUtils 클래스가 없어서 FormulaTest로 변경하고 
CalculateTest 내부의 테스트 하나도 가져오면 좋을 거 같습니다

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Main.java
> +        String formulaString = formula.nextLine();
변수명에 자료형 타입이 오지 않는것이 좋습니다 

이것 역시 저도 받은 코멘트
`타입을 보면 String인걸 알 수 있으니 변수명에 쓸 필요는 없습니다`

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Main.java
> +public class Main {
Main.java 보다는 CalcluatorApplication 와 같이 application이 붙는게 좋다고 합니다

이것도 나도 받았지요 ㅎㅎㅎㅎ
```
application을 붙여주면 다른 역할을 담당하는 클래스와 구분이 더 명확하게 될거에요
StringCalculator 만 쓰면 도메인 객체로 보입니다
```

2020-12-11 01:26 UTC, hhlyn0328 commented on src/main/java/Calculate.java
> +            case "+" :
이 과제의 하이라이트입니다 
다들 이렇게 분기문을 태우는데 8명의 리뷰어가 다 이 방법을 제안합니다 
한 번 츄라이 해보시죠 

------------------
Calculator가 너무 많은 책임을 가지고 있네요
+, -, /, * 같은 연산자를 관리하는 enum 클래스를 추가하면 어떨까요?
```

public enum Operator {

    PLUS("+", (x, y) -> x + y)
    ...

    private final String operator;
    private final BiFunction<Integer, Integer, Integer> function;
    ...

    Operator(String operator, BiFunction<Integer, Integer, Integer> function) {
        this.operator = operator;
        this.function = function;
    }
    public int calculate(int x, int y) {
        return this.function.apply(x, y);
    }
}
```

--------------------

위의 문법이 어색할 수 있는데요 
먼저 , BiFunction<Integer, Integer, Integer> function; 
BiFunction 은 인자가 2개인 함수형 인터페이스를 말해요 3번째 Integer는 return type 입니다

함수형 인터페이스라 하면 장황하고 어려운 거 같지만 
저희가 Interface를 쓰고, 클래스 단위로 implement 하는 것 처럼
method도 파라미터와 return 타입이 똑같은 규칙성 있는 method들에 대해 함수의 interface를 만드는거에요
이 때, 이 인터페이스의 implement는 아래와 같은 람다 문법으로 가능합니다

`BiFunction<Integer, Integer, Integer> function = (num1, num2) -> num1 + num2;`
파라미터와 리턴타입이 인터페이스에서 명시되어있기 때문에 별도의 데이터타입 지정이 생략되었어요
따라서, enum의 두번째 속성이 위의 함수 인터페이스의 구현체가 들어오는 형태라고 보시면 될거 같아요

이 때,  저 함수를 실행시키는 방법은 BiFunction으로 선언한 변수에 .apply (...params) 입니다
위에서는 변수명이 function이라서  this.function.apply(x, y); 이구요


저도 몰랐던 내용이라서 일단 막막하실만한 부분은 좀 더 부연설명을 해봤는데
궁금한게 있으시면 바로 물어보세용

2020-12-11 03:28 UTC, eeunheechoi reviewed
.

2020-12-11 03:28 UTC, eeunheechoi commented on src/main/java/Calculate.java
> +    public static int calculate() {
변경하였습니다.

2020-12-11 06:40 UTC, eeunheechoi commented on src/main/java/Formula.java
> +            Calculate cal = new Calculate(firstNo, sign, lastNo);
위에서부터 적용했는데..그지같던 코드가 이렇게 정리가 되네요 ㅎㅎ;

2020-12-14 01:17 UTC, hhlyn0328 reviewed
피드백 반영을 열심히 해주셨네요 👍 
지금도 훌륭하지만 해보는김에 조금만 더 다듬어보면 더 유연해질 것 같습니다

2020-12-14 01:17 UTC, hhlyn0328 commented on src/main/java/CalculateApplication.java
> +        Scanner input = new Scanner(System.in);
Scanner 변수명은 보통 그냥 scanner를 사용합니당
참고만 해주세요

2020-12-14 01:17 UTC, hhlyn0328 commented on src/main/java/Calculate.java
> +public class Calculate {
클래스명은 보통 명사를 씁니다 Calculator로 변경하면 어떨까요?

2020-12-14 01:17 UTC, hhlyn0328 commented on src/main/java/Calculate.java
> +            case "+" :
연산자 기호에 해당하는 Enum을 찾는 일을 Operator enum에게 메세지를 던져보는 건 어떨까요?
Enum이 실제 어떤 부호들로 구성되어있는지, Calculator 객체가 매칭시켜주는 것보다 Enum이 return 해주는게 자연스러울 것 같아요
저희가 Warehouse에 toEnum을 쓰는 것 처럼요
Enum에 매칭되는 값을 찾을 수 없어서 IllegalArgumentException이 발생하는 부분도 Enum이 처리하는게 자연스러울 것 같습니다

```
public Operator valueOfSign(String sign) {
    switch(sign) {
        case "+": return Operator.PLUS;
}
```

만약, 위처럼 Enum 안에 구현하게 된다면 switch-case 보다 Operator.values()를 스트림으로 탐색한다면,
만약에 사칙연산 외 다른 계산 부호가 추가될 때, Enum의 항목만 추가된다면 다른 부분의 수정은 없어도 될 거 같네요!

2020-12-14 01:17 UTC, hhlyn0328 commented on src/main/java/Operator.java
> +    DIVIDE("/", (x, y) -> x / y);
뒤에 오는 BiFunction 의 구현체는 하나의 method이기 때문에 1줄일 필요는 없습니다 
나눗셈의 뒤의 인자가 0일 때 Exception을 내는 부분이 있는데,  이 validation을 enum안에 private method로 분리하고
DIVIDE 의 calculate function 내부에서 계산전에 이 method를 호출할 수도 있겠네요 

```
DIVIDE("/", (x, y) -> {
    validateDivide(y);
    return x / y ;
});
```

이렇게 수행하게 되면 장점이 위의 연산자를 구분하는 switch-case 문에서 
나눗셈 혼자만 별도의 로직이 있었는데 상관없이 모두 calculate를 호출하면 되겠죠 !

2020-12-14 01:17 UTC, hhlyn0328 commented on src/test/java/CalculateTest.java
> +        int result = Calculate.calculate(4, "/", 2);
divideZeroTest인데, secondNumber가 0도 아니고 검증문도 없어요 ! ㅋㅋㅋ

2020-12-14 01:17 UTC, hhlyn0328 commented on src/test/java/FormulaTest.java
> +        String[] string = {"2","^","3","*","4","/","0"};
뒤에 0으로 나누면 ^ 때문인지 0 때문인지 확인이 안 될 거 같습니다

2020-12-14 01:22 UTC, eeunheechoi commented on src/main/java/CalculateApplication.java
> +        Scanner input = new Scanner(System.in);
네

2020-12-14 01:23 UTC, eeunheechoi commented on src/main/java/Calculate.java
> +public class Calculate {
네

2020-12-14 01:23 UTC, eeunheechoi commented on src/test/java/CalculateTest.java
> +        int result = Calculate.calculate(4, "/", 2);
삭제할 대상이라 삭제하였습니다.

2020-12-14 01:24 UTC, eeunheechoi commented on src/test/java/FormulaTest.java
> +        String[] string = {"2","^","3","*","4","/","0"};
테스트 값에서  0으로 연산하는 부분을 지웠습니다.

2020-12-14 02:03 UTC, hhlyn0328 reviewed
이젠 가독성의 문제니 마지막 코멘트가 될 거 같습니다
첫번째 미션 고생하셨어요 😄

2020-12-14 02:03 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +        return Operator.calculate(Operator.valueOfSign(sign), firstNo, lastNo);
```
Operator operator = Operator.valueOfSign(sign);
return operator.calculate(firstNo, lastNo);
```

또는 

`return Operator.valueOfSign(sign).calculate(firstNo, lastNo);`

가 어떨까요?

2020-12-14 02:03 UTC, hhlyn0328 commented on src/main/java/Operator.java
> +        return x + y;
1줄밖에 없는건 한줄에 표현하는게 더 깔끔해보여요 😅

2020-12-14 02:03 UTC, hhlyn0328 commented on src/main/java/Operator.java
> +        switch (sign) {
```
return Arrays.stream(Operator.values())
			.filter(operator -> operator.operator.equals(sign))
			.findFirst()
			.orElseThrow(IllegalArgumentException::new);
```

이렇게 사용하면 기호가 추가돼도 코드의 추가 수정이 없을 것 같습니다 ㅎㅎ
또는 아래는 어떨까요?

```
for (Operator operator : Operator.values()) {
    if (operator.operator.equals(sign) {
        return operator;
    }
}
throw new IllegalArgumentException();
```

2020-12-14 02:03 UTC, hhlyn0328 commented on src/main/java/Operator.java
> +        if(number !=0 ) {
number가 0일 때 에러를 발생시키고 싶은게 목적이기 때문에 if 문 밖에 default 값이 오는게 좋습니다 
조건을 반대로 주면 좋을 거 같아요

반대로 특정 값만 찾고, 이외에는 다 에러! 라고 하면 지금 형태가 맞겠죠 !

2020-12-14 02:13 UTC, eeunheechoi commented on src/main/java/Operator.java
> +        return x + y;
네

2020-12-14 02:13 UTC, eeunheechoi commented on src/main/java/Calculator.java
> +        return Operator.calculate(Operator.valueOfSign(sign), firstNo, lastNo);
네

2020-12-14 02:20 UTC, eeunheechoi commented on src/main/java/Operator.java
> +        switch (sign) {
네

2020-12-14 02:20 UTC, eeunheechoi commented on src/main/java/Operator.java
> +        if(number !=0 ) {
네

2020-12-14 03:01 UTC, hhlyn0328 commented
고생하셨습니다 :)

2020-12-14 03:02 UTC, merged