add: 사칙연산 개발완료
hhlyn0328/racingcar-practice pull request #2
Opened 2020-12-11 02:18 UTC by updown-kurly

2020-12-11 06:23 UTC, hhlyn0328 requested changes
고생하셨습니다
숫자들, 기호들로 만들어서 인덱스로 접근한다는 생각은 못했는데 신박하네요 😄 
저도 받았던 코멘트들을 참고하여 몇가지 적었습니다 
확인하여 반영해주세요 !

2020-12-11 06:23 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +    public static void main(String[] args) {
main 은 별도로 로직과 분리된 클래스에 위치하는게 좋습니다 
Application 이 뒤에 붙은 클래스를 추가하시면 좋을거 같아요

2020-12-11 06:23 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +public class Calculrator {
하나의 클래스가 너무 많은 역할을 하고 있습니다 
인풋을 입력받고 문자열을 파싱하고 계산하는 것 까지요 
현재 작업 순서를 보면 
1. 문자열을 입력받는다 
2. 부호와 숫자로 파싱한다
3. 부호가 어떤 연산인지 판단한다
4. 계산한다
5. 결과값을 출력한다

로 보이는데 각 단계를 분리해 보시는 연습을 해보시면 좋을 거 같습니다

2020-12-11 06:23 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +    public int calculration(int firstNumber, String symbol, int secondNumber) {
이 과제의 하이라이트입니다 
다들 이렇게 분기문을 태우는데 8명의 리뷰어가 다 이 방법을 제안합니다 
한 번 츄라이 해보시죠 

------------------
Calculator가 너무 많은 책임을 가지고 있네요
+, -, /, * 같은 연산자를 관리하는 enum 클래스를 추가하면 어떨까요?
```

public enum Operator {

    PLUS("+", (x, y) -> x + y)
    ...

    private final String operator;
    private final BiFunction<Integer, Integer, Integer> function;
    ...

    Operator(String operator, BiFunction<Integer, Integer, Integer> function) {
        this.operator = operator;
        this.function = function;
    }
    public int calculate(int x, int y) {
        return this.function.apply(x, y);
    }
}
```

--------------------

위의 문법이 어색할 수 있는데요 
먼저 , BiFunction<Integer, Integer, Integer> function; 
BiFunction 은 인자가 2개인 함수형 인터페이스를 말해요 3번째 Integer는 return type 입니다

함수형 인터페이스라 하면 장황하고 어려운 거 같지만 
저희가 Interface를 쓰고, 클래스 단위로 implement 하는 것 처럼
method도 파라미터와 return 타입이 똑같은 규칙성 있는 method들에 대해 함수의 interface를 만드는거에요
이 때, 이 인터페이스의 implement는 아래와 같은 람다 문법으로 가능합니다

`BiFunction<Integer, Integer, Integer> function = (num1, num2) -> num1 + num2;`
파라미터와 리턴타입이 인터페이스에서 명시되어있기 때문에 별도의 데이터타입 지정이 생략되었어요
따라서, enum의 두번째 속성이 위의 함수 인터페이스의 구현체가 들어오는 형태라고 보시면 될거 같아요

이 때,  저 함수를 실행시키는 방법은 BiFunction으로 선언한 변수에 .apply (...params) 입니다
위에서는 변수명이 function이라서  this.function.apply(x, y); 이구요


저도 몰랐던 내용이라서 일단 막막하실만한 부분은 좀 더 부연설명을 해봤는데
궁금한게 있으시면 바로 물어보세용

2020-12-11 06:23 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +        int temp = numbers.get(0);
temp 보다는 조금 더 의미있는 변수명 이었으면 좋겠습니다

2020-12-11 06:23 UTC, hhlyn0328 commented on src/test/java/CalculratorTest.java
> +    public void calculration() {
calculration  -> calculation 변경 부탁드립니다

2020-12-11 06:23 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +    public List<Integer> getNumbers(String input) {
getSymbols와 getNumbers를 각각 호출하면서  split을 2번하고 비슷한 for문이 2번 도네요 
for(int i = 0; i < length; i++) 형태로 하나씩 증가하되 
아래와 같은 형태의 method를 호출하면 한 번 만 순회 할 수 있지 않을까요?
```
void addComponent(String component, int index)
    if (index % 2 == 1)  {
        this.symbols.add(component);
        return;
    }
    this.numbers.add(component);
}
```

if문안의 조건을 isSymbolIndex 라는 method로 한 번 감싸도 좋을 것 같구요

2020-12-11 06:23 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +        String[] stringArr = input.split(" ");
변수명에 자료형이 추가되어있는 것은 좋지 않다고 합니다
splitedInput 등으로 좀 더 명확한 의미를 나타낼 수 있을 것 같아요

2020-12-14 01:52 UTC, hhlyn0328 reviewed
참고해주세요

2020-12-14 01:52 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +        List<String> symbols = getSymbols(input);
private void parseInput(String input)
... input string > split > 로컬 변수인 numbers, symbols 셋팅

위의 함수 추가하시고, totalCalculation에서는 위의 method 호출하시죠

2020-12-14 01:52 UTC, hhlyn0328 commented on src/main/java/Calculrator.java
> +        int temp = numbers.get(0);
하위의 numbers, symbols -> 내부 변수인 `this.numbers, this.symbols` 사용

2020-12-14 03:52 UTC, hhlyn0328 reviewed
클래스가 잘 나누어졌네요 :) 
지금도 좋지만, 조금만 더 다듬으면 더 유연해질 것 같습니다 !

2020-12-14 03:52 UTC, hhlyn0328 commented on src/test/java/CalculatorTest.java
> +import org.junit.jupiter.api.Test;
클래스 별로 테스트케이스 분리 해주세요

2020-12-14 03:52 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +    void parseInput(String input) {
private / public 접근제어자를 추가해주세요

2020-12-14 03:52 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +        String[] splitedInput = input.split(" ");
split 기준 문자열을 상수로 선언해보는건 어떨까요?
객체지향 생활체조 원칙 3 : 모든 원시값과 문자열을 포장한다 !

2020-12-14 03:52 UTC, hhlyn0328 commented on src/main/java/CalculatorValidationUtil.java
> +public class CalculatorValidationUtil {
해당 유틸이 사용되고 있는곳이 없는거 같습니다

2020-12-14 03:52 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +        switch (symbol) {
이 구조에서 만약 사칙연산외의 계산을 추가하려고 하면 어떻게 될까요?
Calculator 안에 switch-case 문의 case도 추가해야하고, Enum값도 추가해야될 거 같습니다

그렇다면 Enum의 value를 조회해서 Enum을 return 하게 하는건 어떨까요? 
저희 프로젝트의 toEnum 처럼요,  같은 동작에 대한걸 보통 valueOf 라고 칭한다고 하네요
이 경우에는 Operation valueOfSymbol(String symbol) 이 될 수 있겠네요

2020-12-14 03:52 UTC, hhlyn0328 commented on src/main/java/Operator.java
> +    DIVISION("/", (x, y) -> x / y),
0으로 나눴을 때에 대한 validation도 추가되면 좋을 것 같습니다

2020-12-14 03:53 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +                this.symbols.add(splitedInput[i]);
객체지향 생활체조 원칙 1 : 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.
객체지향 생활체조 원칙 2 : else 예약어를 쓰지 않는다.

이 2개를 만족하도록 method를 분리해볼까요?

2020-12-14 07:05 UTC, hhlyn0328 reviewed
한 번 더 ! 👏 
조금만 더 ! 👏

2020-12-14 07:05 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +    final String BLANK = " ";
private static final  으로 해주세요

2020-12-14 07:05 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +        CalculatorValidationUtil calculatorValidationUtil = new CalculatorValidationUtil();
Util을 Instance로 생성할 필요있을까요? 
안의 method를 static으로 선언하고 CalculatorValidationUtil. symbolValidation
이렇게 사용하는게 더 자연스러울 것 같습니다

2020-12-14 07:05 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +            case "+":
이거는 왜 그대로 인가요?
테스트 로직에만 녹이셨네요? ㅋㅋ

2020-12-14 07:05 UTC, hhlyn0328 commented on src/main/java/CalculatorValidationUtil.java
> +    public String symbolValidation(String symbol) {
Enum을 조회할 때 찾지못하면 에러가 날텐데 2번 체크하는 의미가 있을까요?

2020-12-14 08:02 UTC, hhlyn0328 approved these changes

2020-12-14 08:02 UTC, hhlyn0328 commented on src/main/java/Calculator.java
> +    public int totalCalculation(String input) {
이번엔 참고만 하고 넘어가주세요 
public method -> private method -> getter -> setter는 쓰지 않기
순서로 작성하시면 큰 로직부터 읽기가 편할 거 같습니다

2020-12-14 08:02 UTC, hhlyn0328 commented on src/test/java/CalculatorTest.java
> +        assertThat(Operator.PLUS.calculate(1, 2)).isEqualTo(3);
직접 Operator 를 주고 calculate 하는 테스트는 Operator 테스트에서 진행해주시구요 
각 클래스에 있는 method를 호출하여 테스트 할 수 있도록 참고해주세요

2020-12-14 08:02 UTC, hhlyn0328 commented on src/test/java/CalculatorTest.java
> +    public void calculation() {
이게 사칙연산별로 있었다면 좋았겠네요 :)

2020-12-14 08:02 UTC, merged

2020-12-14 08:29 UTC, updown-kurly commented on src/main/java/Calculator.java
> +    public int totalCalculation(String input) {
넵!

2020-12-15 09:52 UTC, updown-90 commented on src/main/java/Calculator.java
> +    public int totalCalculation(String input) {
감사합니다 이부분도 처리하였습니다

2020-12-15 09:52 UTC, updown-90 commented on src/test/java/CalculatorTest.java
> +        assertThat(Operator.PLUS.calculate(1, 2)).isEqualTo(3);
감사합니다 이부분도 처리하였습니다

2020-12-15 09:53 UTC, updown-90 commented on src/test/java/CalculatorTest.java
> +    public void calculation() {
감사합니다 이부분도 처리하였습니다