feat: 자동차 경주 기능 구현
hhlyn0328/racingcar-practice pull request #3
Opened 2020-12-15 09:58 UTC by updown-90

2020-12-16 02:33 UTC, hhlyn0328 reviewed
오 구조가 ! 계산기 때보다 확실히 객체가 잘 나누어진 거 같아요
조금 더 분리되었으면 하는 부분과 일급컬렉션 관련하여 코멘트 남겼습니다
이제는 TDD를 조금 더 연습해보시면 좋을 거 같아요 오늘도 화이팅입니다 😄 

이번 코멘트가 반영되면 랜덤값 테스트에 대한 설명을 드릴게요!
이 부분에 대해서는 너무 깊이 고민하지 마시고 넘어가주세요

2020-12-16 02:33 UTC, hhlyn0328 commented on src/main/java/racingcar/RacingApplication.java
> +        InputView inputView = new InputView();
InputView 내 함수를 static 으로 선언하면 어떨까요?
내부 변수도 없는데 객체로 선언해서 사용할 필요가 없을 거 같아요

2020-12-16 02:33 UTC, hhlyn0328 commented on src/main/java/racingcar/RacingApplication.java
> +        ResultView resultView = new ResultView();
ResultView도 동일할 것 같습니다

2020-12-16 02:33 UTC, hhlyn0328 commented on src/main/java/racingcar/ResultView.java
> +        List<Car> cars = initCars(carCount);
List<Car>를 변수로 갖는 일급컬렉션 Cars를 추가해 보는건 어떨까요?
Cars의 생성자가 initCars를 대체할 수 있을거 같습니다

2020-12-16 02:33 UTC, hhlyn0328 commented on src/main/java/racingcar/ResultView.java
> +            carMove(cars);
Cars가 추가된다면 cars.carMove(); 로 변경할 수 있겠네요

2020-12-16 02:33 UTC, hhlyn0328 commented on src/main/java/racingcar/ResultView.java
> +        for (Car car : cars) {
이 method가 Cars 객체 내부로 이동하게되면 
domain에서 print를 하는 ResultView를 직접호출하게 됩니다 
이를 방지할 수 있는 방법은 무엇이 있을까요?

2020-12-16 02:33 UTC, hhlyn0328 commented on src/test/java/racingcar/RacingCarTest.java
> +public class RacingCarTest {
실제 존재하지 않는 RacingCarTest 말고
Car 테스트와 Cars 가 추가된다면 CarsTest 로 분리되었으면 좋겠네요
`InputView, ResultView(출력만 담당하게된다는 가정), Application 클래스 + 랜덤값 등 테스트가 어려운 클래스`
위의 경우를 제외하고는 클래스 단위로 클래스가 제공하는 가능한 모든 public method에 케이스별로 테스트 코드를 작성해주세요

애초에 가정을 먼저 나열하고 그걸 구현해 나가면 좋을 거 같습니다
기능목록 작성하여 README.md 파일 업데이트 해주세요 

기능 1. 자동차 이동 
  * 4이상이 입력되면 이동횟수가 증가해야한다
  * 4미만이 입력되면 이동횟수가 유지되어야 한다

* 자동차들 이동 
  * 자동차의 수를 입력하면 입력한 수만큼 자동차가 생성되어야한다

등등 ..  그리고 저거를 DisplayName에 일단 넣어서 빈 test를 만들어요 
그리고 다 만족하도록 채워나가시면 좋을거 같아요

2020-12-16 08:05 UTC, hhlyn0328 commented on src/main/java/racingcar/InputView.java
> +        Scanner scanner = new Scanner(System.in);
Sacnner 를 InputView에서는 계속 사용하는데 상수로 선언해두면 어떨까요?

2020-12-16 08:05 UTC, hhlyn0328 commented on src/main/java/racingcar/ResultView.java
> +            car.move(new Random().nextInt(10));
Random Instance 도 계속 생기네요
Random 도 상수로 선언해두고 랜덤숫자 생성 method를 분리하여 호출하면 어떨까요

2020-12-17 03:26 UTC, hhlyn0328 requested changes
피드백 반영을 아주 잘해주셨네요 👍 
몇 가지 조금 더 수정해보면 좋을 것 같은 부분이 있어서 코멘트 남겼어요 

그리고 하나만 더 해볼게요, 현재 ResultView 가 단순 결과 출력 뿐 아니라
경주를 진행하고 있어요 Cars를 생성하고 move를 지시하죠
ResultView가 출력만 담당할 수 있도록 Racing을 진행하는 객체를 하나 더 만들어 보세요 

그리고 trycount 별 advanceCount 들의 변화를 별도의 객체에 저장해서 
마지막 tryCount가 끝났을 때 return 해주세요, 그걸 ResultView가 출력해봅시다

하실 수 있을거라고 믿어요 화이팅 :)

2020-12-17 03:26 UTC, hhlyn0328 commented on src/main/java/racingcar/Cars.java
> +        for (int i = 0; i < this.cars.size(); i++) {
for(Car car: this.cars) 로 하면 get(i)를 쓰지 않아도 될 거 같고, 
혹시나 모를 for문의 조건 실수로 인해 범위를 초과하는 index에 접근하는 경우도 없을 것 같아요

2020-12-17 03:26 UTC, hhlyn0328 commented on src/main/java/racingcar/ResultView.java
> +            getCar(cars);
getCar는 getter의 의미가 강한데 void 네요 
실제로는 출력만 담당하는거 같은데 좀 더 의미가 일치할 수 있는 이름으로 바꿔보면 어떨까요?

2020-12-17 03:26 UTC, hhlyn0328 commented on src/test/java/racingcar/CarsTest.java
> +    void randomTest() {
테스트케이스의 가장 중요한 조건은 언제, 몇 번을 실행해도 결과가 같아야합니다
만약 실제로 우리가 코딩을 잘못해서 랜덤값을 0 ~ 9가 아닌 1~10으로 생성되도록 설정했다고 가정해보죠 
실제로는 10이 생성될 수 있지만 테스트 케이스에서는 수 천, 수 만 번을 반복한다 해도 
0.000000000.....000001의 확률로 10이 나오지 않아 true를 리턴할지도 몰라요 
이 경우에, 우리가 원하는대로 동작한다고 판단하고, 테스트 결과를 신뢰할 수 있을까요?

아니요. 라고 답했다면 이는 테스트 할 수 없는 로직이고, 테스트가 의미 없는 로직인 것 같습니다
이러한 랜덤값의 범위를 테스트하고 싶다면, 예상밖의 값이 Car내부의 move로 넘어가지 않도록 막아주는 방법이 있을 수 있겠네요
Car 내부에서 범위밖의 값이 오면 Exception을 던지게 하고 Car테스트에서 Exception 발생 여부를 테스트 해볼까요?

그렇게 되면 우리가 랜덤함수의 값을 테스트를 통해 확신할 수는 없겠지만 
검증 가능한 메인 비즈니스인 'Car' 자체는 의도하지 않은 값에 의해 이상하게 동작하지는 않을거라는걸 보장할 수 있을 것 같습니다 :)

2020-12-18 08:29 UTC, hhlyn0328 approved these changes
큰 방향은 제가 말씀드린것을 잘 구현하셨네요 
리뷰드린것은 작은 개선 방향이니 다음 미션 때 참고만 하시면 될 거 같습니다
고생하셨어요 :)

2020-12-18 08:29 UTC, hhlyn0328 commented on src/main/java/racingcar/Cars.java
> +        for (Car car : cars.getCars()) {
cars.getCars().strea().map( car -> car.move(randomNumber0To9()).collect(Collectors.toList());
하면 바로 List<CarResult> 가 나올 수 있습니다 
List -> List 의 내부 객체 형변환은 Stream().map 을 쓰는 연습을 좀 더 하시면 좀 더 깔끔합니다

2020-12-18 08:29 UTC, hhlyn0328 commented on src/main/java/racingcar/CarsResultPerTry.java
> +        this.carResultList = carResultList;
이 때, 결과는 수정되면 안되므로 
this.carResultList = Collections.unmodifiableCollection(carResultList) 해주시면 좋습니다

2020-12-18 08:29 UTC, hhlyn0328 commented on src/main/java/racingcar/Race.java
> +        List<CarsResultPerTry> carsResultPerTryList = new ArrayList<>();
이 떄 변수명은 모든 레이싱 결과니까 단순히 carsResultPerTryList 보다는 
그런 의미를 갖는 변수명으로 수정하면 좋지 않을까요?

2020-12-18 08:29 UTC, hhlyn0328 commented on src/main/java/racingcar/RacingApplication.java
> +        Race race = new Race();
Race는 내부 변수가 없는 클래스입니다 
static을 이용하여 변수 선언 없이 호출해볼까요?

2020-12-18 08:29 UTC, hhlyn0328 commented on src/test/java/racingcar/RaceTest.java
> +        assertThat(this.race.racing(race.readyCars(3), 5).size()).
Cars를 생성하는 것은 사전 조건 (give)
race.racing은 검증할 로직의 수행 (when)
확인할 수 있는 결과는 List<CarsResultPerTry>  이므로 
이 3가지가 좀 더 구분되게 작성되면 좋을 거 같아요

```
Cars cars = race.readyCars(3);
assertThat(this.race.racing(cars, 5).size()).isEqualTo(5);  
```
or
```
Cars cars = race.readyCars(3);
List<CarsResultPerTry> results = this.race.racing(cars, 5);
assertThat(results.size()).isEqualTo(5);  

```

2020-12-18 08:29 UTC, merged

2020-12-19 05:01 UTC, updown-kurly commented on src/main/java/racingcar/Cars.java
> +        for (Car car : cars.getCars()) {
감사합니다 해당부분도 처리하였습니다!

2020-12-19 05:05 UTC, updown-kurly commented on src/main/java/racingcar/CarsResultPerTry.java
> +        this.carResultList = carResultList;
네 감사합니다 해당 자료에대해 찾아보고 클래스변수가 List 형식이라 
this.carResultList = Collections.unmodifiableList(carResultList); 부분으로 변경하였습니다.

2021-05-01 07:28 UTC, updown-90 commented on src/test/java/racingcar/RacingCarTest.java
> +public class RacingCarTest {
이랬었다니...

2021-05-01 07:32 UTC, updown-90 commented
리뷰 해주신거 왜 접었죠 다시 다 열건데...ㅋㅋ

2021-05-03 04:15 UTC, hhlyn0328 commented on src/test/java/racingcar/RacingCarTest.java
> +public class RacingCarTest {
ㅋㅋㅋㅋㅋㅋㅋㅋ