feat: STEP4 자동차 경주 우승자 로직 추가
hhlyn0328/racingcar-practice pull request #5
Opened 2020-12-20 04:18 UTC by updown-kurly

2020-12-20 05:00 UTC, hhlyn0328 requested changes
전반적으로 지난번에 짜두었던 기능을 기준으로 잘 반영해주셨네요
이전보다 테스트 케이스 작성이 확실히 잘 된 것이 느껴집니다 😄 
몇가지 추가 코멘트 남겨뒀어요 확인부탁드립니다
String 원시값에 대해 상수화 시켜주시는 부분은 한군데만 코멘트를 남겼는데 전체적으로 확인 한 번 해주세요

그리고 첨부한 이미지는 자동차명 입력받고 parsing 하는 로직의 위치에 대한 제 고민과 
그 답변입니다,   RacingCar는 상하님 로직기준으로 Race에요
참고해주세요 :) 

![image](https://user-images.githubusercontent.com/41069113/102705467-a80ab380-42cb-11eb-9a99-e5f44386c4ce.png)

2020-12-20 05:00 UTC, hhlyn0328 commented on src/test/java/racingcar/CarsResultPerTryTest.java
> +    @DisplayName("생성자 생성할떄 unmodifiableList 정상동작 테스트 ")
오 처음 써보는 method에 대해 테스트 로직을 구현해본 것 아주 칭찬합니다 👍

2020-12-20 05:00 UTC, hhlyn0328 commented on src/test/java/racingcar/RaceTest.java
>  public class RaceTest {
새로추가된 로직들에 대해 테스트 로직이 잘 추가되어있네요 👍

2020-12-20 05:00 UTC, hhlyn0328 commented on src/main/java/racingcar/Race.java
> +    public int maxAdvanceCount(CarsResultPerTry carsResultPerTry) {
maxAdvenceCount를 CarsResultPerTry 에게 물어보면 어떨까요?
일급컬렉션으로 안의 List를 감싸줬는데 다시 접근하는 것보다 내부의 List는 
CarsResultPerTry 에서 접근하고, 결과만 return 해 주는 것이 나을 거 같아요

그리고 stream().mapToInt(CarResult::getAdvanceCount).max() 를 하면 최대값을 뽑아줍니다 
이때 returntype 이 optionalInt 로 되는데 int로 return 하려면 어떻게 하면 될까요? ㅎㅎ

2020-12-20 05:00 UTC, hhlyn0328 commented on src/main/java/racingcar/Race.java
> +        List<CarResult> winnerList = carsResultPerTry.getCarResultList().stream()
이 로직도 마찬가지로 CarsResultPerTry 한테 물어보면 좋을 것 같네요 
그리고 외부에서 알고 싶은 건 우승자의 이름이니 List<String> 형태로 리턴하는건 어떨까요?
최대한 감춰도 되는 정보는 감춰주는게 좋습니다

2020-12-20 05:00 UTC, hhlyn0328 commented on src/main/java/racingcar/ResultView.java
> +    public static void printWinner(List<CarResult> carResultList) {
만약에 return 이 List<String> 으로 변경되면 String.join 으로 printComma를 지울 수 있겠네요 
", " 역시 상수로 한 번 감싸면 우승자 사이를 구분하는 문자가 변경되어야할 때 변경점을 찾기 쉽겠죠?

2020-12-22 10:03 UTC, hhlyn0328 requested changes
고지가 보입니다

2020-12-22 10:03 UTC, hhlyn0328 commented on src/main/java/racingcar/CarsResultPerTry.java
> +        CarsResultPerTry carsResultPerTry = carsResultPerTryList.get(carsResultPerTryList.size() - 1);
carsResultLastTry 등의 느낌으로 마지막 경주 결과임이 변수명에 나타나면 더 좋을 것 같아요

2020-12-22 10:03 UTC, hhlyn0328 commented on src/main/java/racingcar/CarsResultPerTry.java
> +        return carsResultPerTry.getCarResultList().stream()
getAsInt 는 어떤 처리를 해주나요 ?
orElse(0) 만 머릿속에 있었는데 하나를 또 배우네요 👍

2020-12-22 10:03 UTC, hhlyn0328 commented on src/main/java/racingcar/CarsResultPerTry.java
> +                .filter(carResult -> carResult.getAdvanceCount() == maxAdvanceCount(carsResultPerTry))
equals (==) 비교를 여기서 하지않고 carResult에게 maxMoveCount를 던져서 물어볼까요?
이만큼 간 사람이 우승인데, 너는 우승자야?

2020-12-22 10:03 UTC, hhlyn0328 commented on src/main/java/racingcar/CarsResultPerTry.java
> +                .forEach(carResult -> winnerList.add(carResult.getCarName()));
빈 리스트에 add를 해도 되고 stream().map()을 해도 되겠죠?
map 사용을 한 번 연습해보시면 좋을거 같아요

2020-12-22 10:03 UTC, hhlyn0328 commented on src/main/java/racingcar/RacingApplication.java
> +        CarsResultPerTry carsResultPerTry = new CarsResultPerTry();
A라는 객체의 리스트가 있는데
A라는 객체에 거꾸로 A 리스트를 던지면서 우승자를 찾아! 라는건 조금 순환참조되는 느낌이 아닐까요?

List<CarsResultPerTry> 를 갖는 또 하나의 일급컬렉션을 만들어 보면 어떨까요?
이 객체는 이미 List<CarsResultPerTry>를 알고 있어 이 객체에게 우승자를 물어보면 좋을거 같습니다!

2020-12-22 10:03 UTC, hhlyn0328 commented on src/main/java/racingcar/Cars.java
> +        String[] carNames = carNamesString.split(CAR_SEPARATOR);
split을 inputView로 !
Car List 생성을 Stream()으로 작업해보는 연습을 해보시죠

2020-12-22 16:10 UTC, updown-kurly commented on src/main/java/racingcar/CarsResultPerTry.java
> +        return carsResultPerTry.getCarResultList().stream()
max() 가 OptionalInt 를 return 하고있어 getAsInt() 를 사용하면 OptionalInt 값을 int 값으로 추출할수 있습니다

참고 )
OptionalXXX 의 종류 : Optional, OptionalDouble, OptionalLong, OptionalInt 클래스 타입
이 객체에서 값을 얻으려면 get(), getAsDouble(), getAsInt(), getAsLong()를 호출.

2020-12-22 16:21 UTC, updown-kurly commented on src/main/java/racingcar/CarsResultPerTry.java
> +                .filter(carResult -> carResult.getAdvanceCount() == maxAdvanceCount(carsResultPerTry))
이런 사고를 가지기가 참 어려운것 같습니다 객체의 역할이라고 해야하나요? 아니면 객체지향적인 설계? ㅠㅠ

2020-12-22 16:28 UTC, updown-kurly commented on src/main/java/racingcar/CarsResultPerTry.java
> +                .filter(carResult -> carResult.getAdvanceCount() == maxAdvanceCount(carsResultPerTry))
말씀주신부분 참고하여 처리하였습니다!

2020-12-23 05:43 UTC, hhlyn0328 commented on src/main/java/racingcar/CarsResultPerTry.java
> +        return carsResultPerTry.getCarResultList().stream()
그럼 Integer가 Null인 경우는 오류안나나요 ?
Optional.empty() 를 get() 시도 했을 때 발생하는 오류요

2020-12-23 05:52 UTC, updown-kurly commented on src/main/java/racingcar/CarsResultPerTry.java
> +        return carsResultPerTry.getCarResultList().stream()
NoSuchElementException 이 발생하는데
일부러 빈 값을 넘겨서 받을경우는 없다고 생각하여 getAsInt() 를 사용하였는데
좀더 확실하게 하려면 orElse(0) 이 좋을것 같습니다!
아래 코드로 테스트 하였습습니다!
![image](https://user-images.githubusercontent.com/67937851/102964259-82311900-452e-11eb-83e4-20f367744aa1.png)

2020-12-23 05:53 UTC, hhlyn0328 reviewed
나머지는 자잘한 수정이라서 approved 드리려고 했는데
자동차 이름 5자이상 불가 요구사항이 있었던거 같은데 지난 리뷰들에서 제가 깜빡한 거 같아요 
관련 내용 추가해주시면 이젠 진짜 머지 갈 것 같습니다 !

2020-12-23 05:53 UTC, hhlyn0328 commented on src/main/java/racingcar/RaceWinner.java
> +                .filter(carResult -> carResult.isWinner(carsResultLastTry.maxAdvanceCount()))
max값을 변수에 담아놓고 사용하면 어떨까요? 
carResult 마다 max 값을 구하는 연산을 반복할 거 같아요

2020-12-23 05:53 UTC, hhlyn0328 commented on src/main/java/racingcar/RaceWinner.java
> +    private List<CarsResultPerTry> winnerList;
회차별 결과의 목록이 우승자의 목록일까요?
carsResults 라고만 쓰는게 맞을 거 같아요 

마지막 경주에서만 winner를 뽑아내는 거고 그 우승자의 목록이 winnerList라는 변수명이 더 맞을 거 같습니다

2020-12-23 05:53 UTC, hhlyn0328 commented on src/main/java/racingcar/RaceWinner.java
> +                .map(carResult -> carResult.getCarName())
carResult -> carResult.getCarName() 는
CarResult::getCarName  으로 변경할 수 있습니다 

이 때 얻는 이점은, param 없어 무의미한 괄호가 제거되어 가독성이 높아지는 것 정도일까요?
익숙해지시면 좋을 거 같습니다

2020-12-24 02:16 UTC, hhlyn0328 approved these changes
끗- 고생하셨습니다 👍

2020-12-24 02:16 UTC, merged