feat: step4 레이싱 기능 구현
hhlyn0328/racingcar-practice pull request #6
Opened 2020-12-21 06:49 UTC by eeunheechoi

2020-12-21 15:39 UTC, hhlyn0328 requested changes
전반적으로 상수의 선언과 일급 컬렉션을 사용하는 부분이 조금은 눈에 보이시는거 같아요 
저도 보면서 또 느끼고 배우게 되네요 

특히 저는 입력받은 차량의 이름을 Race 클래스에서 진행해서 넘겼었는데 
그 때 받았던 코멘트가 아래와 같습니다 
그런데 은희님은 알아서 InputView 에서 처리해주셨네요 👍 
![스크린샷 2020-12-20 오후 1 59 42](https://user-images.githubusercontent.com/41069113/102794071-26f80d00-43ee-11eb-965f-b21dbf28a726.png)

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/CarRacingResultsByRound.java
>          this.carRacingResults = carRacingResults;
일급컬렉션의 경우 생성 이후에 리스트자체가 수정될 일은 없어야 하기 때문에
this.carRacingResults = Collections.unmodifiableList(carRacingResults);
과 같이 불변 리스트로 만들어줄 수 있습니다

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/Cars.java
> +    private static final int MAX_NUMBER = 9;
변경된 값이 의미에 더 맞아보이네요 👍

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/Cars.java
> +    private static final int CAR_NAME_LENGTH_LIMIT = 5;
기준에 대한 상수처리 좋습니다 👍

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/FinalRoundResult.java
> +        OptionalInt maxMoveCountOptional  = this.finalRoundResult.getCarRacingResults().stream()
Stream().max() 를 통한 접근 좋았습니다 👍 
orElse가 아래에 붙어있는데 이쪽에 붙어있으면 return type이 int가 될 수 있지 않을까요? ㅎㅎ

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/FinalRoundResult.java
> +    public List<CarRacingResult> getWinnerList() {
우승자의 이름만 전달하도록 해볼까요?
CarRacingResult도 직접 전달하지 않기위해서 이리저리 감쌌는데 
다시 가장 내부의 결과를 그대로 전달하고 있어서 필요한 값만 방어적으로 전달하면 좋을 거 같습니다

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/InputView.java
> +        return scanner.nextLine().split(",");
split의 기준이되는 문자열도 상수로 선언하면 좋을 것 같습니다

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/Race.java
> +            if(this.raceCount -1 == i) {
indent가 2가 되었네요 
마지막 라운드는 raceCount-1이 거나, result List의 size() -1 이겠죠?
그렇다면 반복문을 다 돌고 난 다음에도 접근할 수 있지 않을까요?

그리고 RacingAllResult 생성자에서도 carRacingResultsByRounds 의 리스트를 전달받았다면 
그 중의 마지막에 접근하여 알 수 있지 않을까요?

리스트는 기본적으로 특별한 정렬을 하지 않는 이상 add를 하는 순서대로 저장합니다 
for문이 돌면서 실제로 수행하는 레이스의 순서와 결과가 만들어진 List의 index가 일치하지 않을까 걱정하셨다면 
ArrayList나, LinkedList를 쓸 때는 중간에 정렬을 하지 않는 이상 고려하지 않으셔도 될 것 같아요

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/Race.java
> +    private RacingAllResult racingAllResult;
RacingAllResult 만든것 좋았습니다 👍

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/ResultView.java
> +        for(int i=0; i<finalRoundResult.getWinnerList().size(); i++) {
우승자 이름만 String List로 return 받게 된다면 
String.join(",", winners);을 사용해보세요 

혹은 여기서 getWinnerList().stream().map( ?????? ).collect(Collectors.joining(","));
이렇게 map을 통해서 carName을 뽑아낸 뒤, Collectors.joining 을 통해 String 결과값을 받을 수 있습니다

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/Cars.java
> +        for(int i=0; i< carNames.length; i++) {
Arrays.stream(carNames)  를 통해서 배열도 stream 연산이 가능합니다 
Cars 생성자에 대한 테스트케이스도 작성되어있으니 
문법 연습 겸, stream으로 생성해보도록 연습해볼까요?

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/Cars.java
>          int randomNumber = random.nextInt(9);
요기의 9도 상수재활용이 가능할 거 같아요 !

2020-12-21 15:39 UTC, hhlyn0328 commented on src/main/java/race/FinalRoundResult.java
> +                .filter(carResult -> carResult.getMoveCount() == maxMoveCountOptional.orElse(0))
이건 저도 그렇게 안했는데.. 문득 든 생각인데 
carResult 에 isWinner(int maxMoveCount) 가 있음 좋겠네요 
winner의 숫자와 같다면 true 아님 false

2020-12-23 01:17 UTC, eeunheechoi commented on src/main/java/race/CarRacingResultsByRound.java
>          this.carRacingResults = carRacingResults;
네

2020-12-23 01:19 UTC, eeunheechoi commented on src/main/java/race/FinalRoundResult.java
> +        OptionalInt maxMoveCountOptional  = this.finalRoundResult.getCarRacingResults().stream()
.max() 리턴 타입이 OptionalInt 이라서 .orElse(0)을 하니 타입오류가 나네요

2020-12-23 01:28 UTC, eeunheechoi commented on src/main/java/race/FinalRoundResult.java
> +    public List<CarRacingResult> getWinnerList() {
네

2020-12-23 01:30 UTC, eeunheechoi commented on src/main/java/race/InputView.java
> +        return scanner.nextLine().split(",");
네

2020-12-23 01:36 UTC, eeunheechoi commented on src/main/java/race/Race.java
> +            if(this.raceCount -1 == i) {
네

2020-12-23 01:41 UTC, eeunheechoi commented on src/main/java/race/ResultView.java
> +        for(int i=0; i<finalRoundResult.getWinnerList().size(); i++) {
String.join(",", winners); 이걸 알았으면 출력에 시간이 많이 안들었을건데 ㅎㅎ 멋지네요.

2020-12-23 01:44 UTC, eeunheechoi commented on src/main/java/race/Cars.java
>          int randomNumber = random.nextInt(9);
네

2020-12-23 01:50 UTC, eeunheechoi commented on src/main/java/race/Cars.java
> +        for(int i=0; i< carNames.length; i++) {
네

2020-12-23 01:56 UTC, eeunheechoi commented on src/main/java/race/FinalRoundResult.java
> +                .filter(carResult -> carResult.getMoveCount() == maxMoveCountOptional.orElse(0))
네

2020-12-23 05:29 UTC, hhlyn0328 commented on src/main/java/race/FinalRoundResult.java
> +        OptionalInt maxMoveCountOptional  = this.finalRoundResult.getCarRacingResults().stream()
return this.results.stream()
			.mapToInt(RacingResult::getMoveCount)
			.max().orElse(0);
			
			저는 이렇게 처리했는데 안되나요?

2020-12-23 05:40 UTC, hhlyn0328 approved these changes
피드백을 잘 반영해주셨네요 👍 
몇가지 진짜 정말 완전 자잘한 코멘트만 남아서 우선 승인해드릴게요
다음에 푸시하시면 바로 머지 갑니다잉

2020-12-23 05:40 UTC, hhlyn0328 commented on src/main/java/race/Cars.java
> +                .map(carName -> {
아 이런 저번 리뷰에 놓쳤네요 
length체크는 Car내부로 가서 Car생성자에서 validation하는게 더 맞아보여요

2020-12-23 05:40 UTC, hhlyn0328 commented on src/main/java/race/FinalRoundResult.java
> +                .map(winner -> winner.getCarName())
param이 없는 method는  
winner -> winner.getCarName() 을
Winner::getCarName 이라고 변경할 수 잇습니다 

장점은 param이 없기 때문에 무의미한 괄호의 제거로 인한 가독성 증가랄까요 ㅎㅎ

2020-12-23 05:40 UTC, hhlyn0328 commented on src/main/java/race/FinalRoundResult.java
> +        OptionalInt maxMoveCountOptional  = this.finalRoundResult.getCarRacingResults().stream()
네 그래서 앞에 return 받는 아이도 int 로 변경되어야해요
int max = stream().mapToInt().max().orElse(0) 으로요 !
그럼 아래 25라인에서 비교할때 orElse를 제거할 수 있어요

2020-12-23 05:55 UTC, eeunheechoi commented on src/main/java/race/FinalRoundResult.java
> +        OptionalInt maxMoveCountOptional  = this.finalRoundResult.getCarRacingResults().stream()
네

2020-12-23 05:58 UTC, eeunheechoi commented on src/main/java/race/Cars.java
> +                .map(carName -> {
네

2020-12-23 06:01 UTC, eeunheechoi commented on src/main/java/race/FinalRoundResult.java
> +                .map(winner -> winner.getCarName())
네

2020-12-23 06:16 UTC, merged